openai:
  secret-key : ${GPT_KEY}
  url:
    model : https://api.openai.com/v1/models
    model-list : https://api.openai.com/v1/models/
    legacy-prompt: https://api.openai.com/v1/completions
    prompt : https://api.openai.com/v1/chat/completions
