openai:
  secret-key : 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
  url :
    model : https://api.openai.com/v1/models
    model-list : https://api.openai.com/v1/models/
    legacy-prompt: https://api.openai.com/v1/completions
    prompt : https://api.openai.com/v1/chat/completions
